// packages/editor-react/src/lib/hooks/slate/use-editor-node-ref.ts
import { useLayoutEffect, useRef } from 'react';
import { ReactEditor } from 'slate-react';
import { useEditor } from './use-editor';

export function useEditorNodeRef() {
  const editor = useEditor();
  const editorNodeRef = useRef<HTMLElement | null>(null);

  useLayoutEffect(() => {
    editorNodeRef.current = ReactEditor.toDOMNode(editor, editor);
  }, [editor]);

  return editorNodeRef;
}

// packages/editor-solid/src/lib/hooks/slate/use-editor-node-ref.ts
import { useEditor } from './use-editor'
import { createEffect } from 'solid-js'
import { SolidEditor } from 'slate-solid'

export function useEditorNodeRef() {
  let editorNodeRef: HTMLElement | null = null

  createEffect(() => {
    const editor = useEditor()
    editorNodeRef = SolidEditor.toDOMNode(editor, editor)
  })

  return editorNodeRef
}
