// packages/editor-solid/src/features/left-controls/controls/context.ts
import type { ControlsState } from './types'
import { createContext, useContext } from 'solid-js'

const ControlsContext = createContext<ControlsState>({} as ControlsState)

export const ControlsProvider = ControlsContext.Provider

export function useControlsState() {
  return useContext(ControlsContext)
}

// packages/editor-react/src/features/left-controls/controls/context.ts
import { createContext, useContext } from 'react';
import type { ControlsState } from './types';

const ControlsContext = createContext<ControlsState>({} as ControlsState);

export const ControlsProvider = ControlsContext.Provider;

export function useControlsState() {
  return useContext(ControlsContext);
}
